version: '3'

services:
  rundeck:
    image: rundeck/rundeck:5.2.0-20240410
    environment:
      RUNDECK_GRAILS_URL: http://localhost:4440
      RUNDECK_SERVER_FORWARDED: true
      RUNDECK_DATABASE_DRIVER: org.h2.Driver
      RUNDECK_DATABASE_URL: jdbc:h2:file:/home/rundeck/server/data/grailsdb
      RUNDECK_DATABASE_USERNAME: sa
      RUNDECK_DATABASE_PASSWORD: ''
    ports:
      - "4440:4440"
    volumes:
      - rundeck-data:/home/rundeck/server/data
      - rundeck-config:/home/rundeck/server/config
      - rundeck-logs:/home/rundeck/server/logs

volumes:
  rundeck-data:
  rundeck-config:
  rundeck-logs:
